services:
  zoo:
    image: zookeeper:3.8
    restart: unless-stopped
    environment:
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
  solr:
    image: solr:8
    restart: unless-stopped
    ports:
      - 8983:8983
    environment:
      SOLR_HEAP: 2g
      ZK_HOST: zoo:2181
    command: -c
    volumes:
      - solr_data:/var/solr
  roda:
    image: ghcr.io/keeps/roda:v4
    restart: unless-stopped
    ports:
      - 8080:8080
      - 5005:5005 # remote debug
    depends_on:
      - solr
    environment:
      # Solr Cloud configuration
      - RODA_CORE_SOLR_TYPE=CLOUD
      - RODA_CORE_SOLR_CLOUD_URLS=zoo:2181
      - SOLR_NUM_SHARDS=4
      - SOLR_MAX_SHARDS_PER_NODE=4
      - SOLR_REPLICATION_FACTOR=1

      # Remote debug
      - JPDA_ADDRESS=5005
      - JPDA_TRANSPORT=dt_socket
    volumes:
      - roda_data:/roda/data
    command: catalina.sh jpda run
  swagger:
    image: swaggerapi/swagger-ui
    restart: on-failure
    ports:
      - 8081:8080
    environment:
      - URL=http://localhost:8080/api/openapi.json
      - DOC_EXPANSION=none
      - VALIDATOR_URL=none
volumes:
  zookeeper_data:
  zookeeper_datalog:
  solr_data:
  roda_data:
