services:
  zoo:
    image: zookeeper:3.8
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
  solr:
    image: solr:8
    restart: unless-stopped
    ports:
      - "8983:8983"
    environment:
      ZK_HOST: zoo:2181
      SOLR_HOST: localhost
    depends_on:
      - zoo
    command:
      - -c
    volumes:
      - solr_data:/var/solr

volumes:
  zookeeper_data:
  zookeeper_datalog:
  solr_data:
